#!/usr/bin/perl
##################################################################################
# Copyright (C) 2010  Chris Rutledge <rutledge.chris@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
##################################################################################
use strict;
use lib "/usr/local/lib/perl";
use APSH;

##############################
# Error checking
##############################
if (! $ARGV[0] || ! $ARGV[1]){
   print STDERR "Usage: apsh <NODEORGROUP[,NODEORGROUP[,..]]> <CMD>\n";

   if($ARGV[0]){
      print STDERR "\nERROR: no command to run!\n";
   }

   exit(1);
}

##############################
# Global Variables
##############################
my @NODES      = APSH::GenNodes($ARGV[0]);
my $CMD        = APSH::QuoteCMD($ARGV[1]);
my $COLOR      = undef;

if ($ARGV[2] =~ /c/){
   $COLOR = "1";
}else{
   $COLOR = "0";
}

APSH::CreateThreads(@NODES);

##############################
# RunCMD()
#
# Get $HOST and $USER from string
# passed and run the command.
##############################
sub RunCMD {
   my (@NODECFG) = split(/:/, $_[0]);

   my $PADDING = APSH::GetPadding($NODECFG[0]);

   open(FH, "ssh -o BatchMode=yes -l $NODECFG[1] $NODECFG[0] $CMD 2>&1 |");

   while(<FH>){
      if ($ENV{'TERM'} eq "xterm" && $COLOR){
         print "\033\[$NODECFG[3]m$NODECFG[0]:\033\[0m $PADDING$_";
      }else{
         print "$NODECFG[0]: $PADDING$_";
      }
   }

   close(FH);
}
